### ISSUE TITLE
Reviewer

### ISSUE THREAD

**Issue by dnxjay** [ubsuny/CP1-24-HW2#24]
What is the expectation from the reviewers?

**Comment by avgagliardo** [comment]
Minimally we should take a look at the changes, assess if they make sense, and if the changes do what the commit messages say they are supposed to do (otherwise it may have been pushed accidentally).

If it's code, sometimes it's more practical to try and run the changes yourself to see if anything significant breaks or changes rather than just eyeball it from the code.

**Comment by dnxjay** [comment]
Okay makes sense just wanted to be sure about that. Thanks for the reply!
