### ISSUE TITLE
Invalid Notebook

### ISSUE THREAD

**Issue by haiderabbas007** [ubsuny/CP1-24-HW2#31]
![image](https://github.com/user-attachments/assets/7feb887d-3ac9-478b-9167-e073f3957ccc)

**Comment by ojha-aditya** [comment]
Was this before the .devcontainer file was added for Python or are you unable to sync your codespace changes?

**Comment by p-pxmpo** [comment]
It could be that the .ipynb file is saved in JSON format, and if the file structure gets corrupted, Jupyter will not be able to open it.

**Comment by ojha-aditya** [comment]
Yes it could also be due to the file structure, I had actually come across the same in HW 1. I guess I will put it in a separate issue in detail, I remember having a discussion with @laserlab about the same.

**Comment by avgagliardo** [comment]
Oh that was actually just a stubbed file. It says invalid because its not a well-formed notebook file like the extension indicates. 

Since it was just a placeholder to indicate where the notebooks could live in this project, feel free to delete/replace it.

**Comment by avgagliardo** [comment]
I think I mentioned in the PR that it was a placeholder file, but I should have specified that since its a blank file (with the .ipynb extension) it doesn't actually do anything.

**Comment by ojha-aditya** [comment]
That is right. This is how it shows all .ipynb extension files that have been given the extension manually unless formatted in codespace/any other editor. 

There is another interesting thing that was encountered in the previous homework and I had a discussion with @laserlab about it. If we create a file like this placeholder file, and then edit it using a codespace, the code format of the Jupyter notebook contains all code in a single line instead of being well indented.

**Comment by haiderabbas007** [comment]
Thank you everyone for the input and clarification.
