### ISSUE TITLE
Codespace Python Environment

### ISSUE THREAD

**Issue by ojha-aditya** [ubsuny/CP1-24-HW2#52]
We have so far preferred using the Global environment when selecting the Python kernel for our codespaces. I had a doubt, however, that if the local and global environments are the same (Python 3.11.2 for example), does it make a difference still?
On an implementation level what is the difference between these two?

**Comment by p-pxmpo** [comment]
if you prefer reproducibility and isolated work I would just use a local environment

**Comment by avgagliardo** [comment]
If you are ever unsure what version of python is installed to an environment you can always test it with `python –version` or `python -V`

Alternatively, if you are inside of a python interpreter (or a jupyter notebook) you can find the version with:

`import sys              #import the python runtime module`
`print(sys.version)      #print the version of python currently running`

**Comment by ojha-aditya** [comment]
Alright! So it affects only on the part of isolation of the work and not other than that if the two versions (i.e. local and global) are the same?

**Comment by avgagliardo** [comment]
Virtualization is a little bit of a convoluted topic because of the number of different ways that containers/virtual environments can exist, but generally speaking the reason why you would virtualize in a local directory is because you want to use a specific subset of packages/modules that corresponds to a certain project or branch.

Extending beyond that, you generally want to try and keep your whole project/system executing within the same virtual env since you can run into a lot of confusion if part of it is running inside of one virtualization while another uses a different set of dependencies. It just becomes very difficult to troubleshoot and maintain.

**Comment by ojha-aditya** [comment]
I get it. So we have been using global environments only for maintaining uniformity but in order to  project specific packages we would virtualize in a local environment and then use project actions as you mentioned in #50 ?

**Comment by avgagliardo** [comment]
> I get it. So we have been using global environments only for maintaining uniformity but in order to use project specific packages we would virtualize in a local environment and then use project actions as you mentioned in #50 ?

that is one type of architecture-- usually you virtualize an env within the global env to give yourself a clean space to work within (no external package conflicts or unknown modules being used) during development. 

What I was talking about in #50 is kind of related to the opposite end of things-- you automate the build for different target environments to make sure that people who are going to use your software will be able to do it across a number of different platforms and environments (depending on how you configure the workflow), in addition to making sure that it still runs on the platform you were using during development.

I know its kind of confusing, but its a lot easier to keep track of when you see a tangible example.

**Comment by ojha-aditya** [comment]
I understand now. Thank you very much for the explanation!
