### ISSUE TITLE
Diagonal of an n-dim object?

### ISSUE THREAD

**Issue by avgagliardo** [ubsuny/CP1-24-HW2#58]
I see that some of the numpy methods extend to n-dim array objects. I wanted to check that my understanding of a diagonal for higher-dimensional objects is correct: 

Let's say we have an n-dimensional array, then we will define **q = m - 1** where m is the number of elements in the smallest dimension of the object. So for a 5x6x7x8 array, we would have q=4.

Then to build our diagonal, we would construct the list of values from the points in the matrix where each of the n-index values are equal. For example,  [(0,0,0,0), (1,1,1,1), (2,2,2,2),... (q,q,q,q)].

**Comment by ojha-aditya** [comment]
Yes, this is generally used for Tensorial calculation if I am correct. We basically define a diagonal tensor $T$ of order $n$, as a tensor with all components zero, except the ones for which all indices $i_1, i_2, ... , i_n$ are equal. In an array format this is how it would translate I believe.

**Comment by avgagliardo** [comment]
Awesome, thanks!

**Comment by HeshamElsaman** [comment]
I'm just commenting for the sake of enhancing my understanding or sth. I'm not quite convinced that you can define a diagonal for any object the same way it is defined for matrices. Because, even for matrices, the diagonal is defined for if the dimensionality is the same for both indices. For instance, I can't say for sure that a 5x6 matrix has a diagonal because then I can equally claim it might have multiple diagonals since the line of equal indices does not split the matrix symmetrically.

On another hand, we need to distinguish between the rank and dimensionality. Simply put, the rank is the number of indices a mathematical object can have, and dimensionality is the degrees of freedom for each index. A matrix is always a second rank object, but its dimensionality may differ. That's why I regard the terminology of n-dimensional arrays as inaccurate.

For a higher-rank object I can claim the same that we cannot define a diagonal the same way we did with matrices unless compared to square matrices, and only then we can say that we can define a diagonal only for objects which possess the same number of degrees of freedom for each index. That's at least strictly speaking of the notion of the (diagonal). However, if it's just for convenience that we want to define some (main diagonal) for a rectangular matrix for example, then I guess I can go with that.

I haven't read a lot about it, so I just loved to share what I'm thinking about it in getting to know more from you. A formal reference tackling this topic would be of great help as well if any of you can suggest one or several.

**Comment by ojha-aditya** [comment]
Having a notion of diagonal is still possible for such objects say an $n \times m$ matrix. There is a something known as a singular value decomposition, which can factorize it in a form which can be then regarded as diagonal.
